# Generated by Django 5.0.6 on 2024-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_date', models.DateField(max_length=10)),
                ('product_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('revision', models.CharField(max_length=100)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('address_street', models.CharField(max_length=100)),
                ('address_building', models.CharField(max_length=100)),
                ('address_apartment', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_postal_code', models.CharField(max_length=100)),
                ('address_country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('auction_name', models.CharField(max_length=100)),
                ('additional_info', models.TextField(max_length=1000)),
                ('gps_latitude', models.FloatField(max_length=100)),
                ('gps_longitude', models.FloatField(max_length=100)),
            ],
        ),
    ]
