# Generated by Django 5.0.6 on 2024-07-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='additional_info',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='record',
            name='address_apartment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='address_building',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='address_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='address_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='auction_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='revision',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
