# Generated by Django 5.0.7 on 2024-07-12 20:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_record_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
